### ISSUE TITLE
ERROR: could not get url for device (since 11.2.6)

### ISSUE THREAD

**Issue by Patt92** [encounter/tsschecker#11]
Hello,

I'm using tsschecker (v268) for a few weeks now. Starting 11.2 I saved the blobs with tsschecker.
Since 11.2.6 I only get this error:

[TSSC] manually specified ecid to use, parsed "xxxx" to dec:xxxxx hex:xxxx
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] ERROR: could not get url for device iPhone7,2 on iOS 15D100
[Error] [TSSC] checking tss status failed!

[TSSC] manually specified ecid to use, parsed "xxxx" to dec:xxxxx hex:xxxx
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] ERROR: could not get url for device iPhone9,3 on iOS 15D100
[Error] [TSSC] checking tss status failed!

Working fine, when downloading 11.2.5 blobs though.

Tried with 28 devices (15x iPhone 6, 9x iPhone 6S and 4x iPhone 7)
I'm using it on my Ubuntu 16.04 server (self compiled and working smoothly).
The OTA blobs work, but they look way smaller, than the restore blobs and I guess they won't work for futurerestore.

Anyway the same result is on my Macbook Pro (2017), RaspberryPI and Windows server.
Someone experiencing the same result? Known issue or some strange behavior?

**Comment by tvosrepo** [comment]
Having the same issue with Apple TV 4K and tvOS 11.2.6

**Comment by ghost** [comment]
Same here

**Comment by Patt92** [comment]
has been strangely resolved, when 11.3 dropped. 11.2.6 is also saved
