### ISSUE TITLE
I Come Back

### ISSUE THREAD

**Issue by xybp888** [encounter/tsschecker#3]
is error :
checking pkg-config is at least version 0.9.0... yes
checking for libplist >= 1.11... no
configure: error: Package requirements (libplist >= 1.11) were not met:

No package 'libplist' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libplist_CFLAGS
and libplist_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by xybp888** [comment]
config.status: creating fuzz/Makefile
config.status: creating doxygen.cfg
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Configuration for libplist 2.0.0:
-------------------------------------------
libplist log: 
  Install prefix ..........: /mingw
  Debug code ..............: no
  Python bindings .........: no

  Now type 'make' to build libplist 2.0.0,
  and then 'make install' for installation.

Making install in libcnary

**Comment by encounter** [comment]
After running `make install` for libplist, run `./autogen.sh` for tsschecker again.

**Comment by xybp888** [comment]
run this :
git clone https://github.com/libimobiledevice/libplist.git
cd libplist
sed -ie 's/typedef volatile struct {/#elif 0/g' src/plist.c #dirty hack to make other projects, depending on this, work
./autogen.sh --host=x86_64-w64-mingw32 -without-cython --enable-static --disable-shared  --prefix=/mingw
make install
cd ..

**Comment by encounter** [comment]
Are you using msys2+mingw64 on Windows? If so, it should be as simple as this:

```
git clone https://github.com/libimobiledevice/libplist.git
cd libplist
./autogen.sh
make install
```

**Comment by xybp888** [comment]
Yes, me Using msys2+mingw64 On Windows

**Comment by encounter** [comment]
Ah, I just noticed the Windows build instructions in the repo. For the most part you can ignore that, and just install the required libs using the standard commands I posted above. Much cleaner than trying to cross compile, doesn't require all the weird hacks.

**Comment by xybp888** [comment]
Oh,I see!
install log: 
checking for libplist >= 1.0... yes
Success
thank You so much!

**Comment by xybp888** [comment]
omg! 
I have installed libcurl-7.57.0-1
Why is it still a hint
checking for libcurl >= 1.0... no

**Comment by encounter** [comment]
Hm, try this:

```
git clone https://github.com/Alexpux/MINGW-packages.git
cd MINGW-packages/mingw-w64-curl
# EDIT PKGBUILD to use _variant=-winssl
makepkg-mingw -is
```

**Comment by xybp888** [comment]
It is no use!

**Comment by xybp888** [comment]
I used this msys2+mingw64 for the first time.
Please contain me :)

**Comment by xybp888** [comment]
==> validating source documents, the use of sha256sums...
Curl-7.57.0.tar.bz2... Through
Curl-7.57.0.tar.bz2.asc... Already skipped
0001-Make-cURL-relocatable.patch... Through
==> is using the GPG source file signature verification...
Curl-7.57.0.tar.bz2... Failure (unknown public key 5CC908FDB71E12C2)

==> error: one or more PGP signature could not be verified!

**Comment by encounter** [comment]
Run `gpg --recv-key 5CC908FDB71E12C2`

**Comment by xybp888** [comment]
==> error: in prepare (in) an error occurred.

**Comment by xybp888** [comment]
/home/Administrator/MINGW-packages/mingw-w64-curl/PKGBUILD:row 54: patch: No command

**Comment by encounter** [comment]
`pacman -S patch`

**Comment by xybp888** [comment]
Thank You Today !

**Comment by xybp888** [comment]
../external/libfragmentzip/libfragmentzip/.libs/libfragmentzip.a(libfragmentzip_la-libfragmentzip.o): In function `fragmentzip_download_file':
D:\msys64\home\Administrator\libfragmentzip\libfragmentzip/libfragmentzip.c:261: undefined reference to `inflateInit2_'
D:\msys64\home\Administrator\libfragmentzip\libfragmentzip/libfragmentzip.c:268: undefined reference to `inflate'
D:\msys64\home\Administrator\libfragmentzip\libfragmentzip/libfragmentzip.c:270: undefined reference to `inflateEnd'
D:\msys64\home\Administrator\libfragmentzip\libfragmentzip/libfragmentzip.c:280: undefined reference to `crc32'

**Comment by encounter** [comment]
That one's my fault... edit `external/libfragmentzip/libfragmentzip/Makefile.am` and on line 2, change `zlib_CFLAGS` to `zlib_LIBS`. I'll have that fixed in the repo soon.

**Comment by xybp888** [comment]
AM_CFLAGS = $(zlib_LIBS) $(curl_CFLAGS) -I$(top_srcdir)/include
AM_LDFLAGS = $(zlib_LIBS) $(curl_LIBS) 
??

**Comment by encounter** [comment]
Only the second line

**Comment by xybp888** [comment]
libfragmentzip.c:21:26: error: size of array 'assertion_failed_fragmentzip_cd_size_is_wrong_118' is negative
 typedef char _impl_PASTE(assertion_failed_##file##_,line)[2*!!(predicate)-1];

**Comment by encounter** [comment]
OK, I pushed a new commit to libfragmentzip that should fix the Windows errors. Try pulling those changes.

**Comment by xybp888** [comment]
Success!!! 
Finally, Finally,Finally
perfect!!
Thank You very much!　Today!!!! 
Thank you for your patience to help me with this compilation
So tired! ! !  

I am Chinese
I'm not good at English!
Finally, with your help, this compilation is completed. Thank you very much!
In China, bbs.feng.com this BBS
Many people are using the  you compiled tsschecker for Windows
Thank you so much


Administrator@GaChSrc MINGW64 ~/tsschecker
$ tsschecker
Version: 826cdc6d8c2bff7cb3c160f000212bedf60c0bbb - 264
Usage: tsschecker [OPTIONS]
Checks (real) signing status of device/firmware

  -d, --device MODEL            specific device by its MODEL (eg. iPhone4,1)
  -i, --ios VERSION             specific iOS version (eg. 6.1.3)
      --buildid BUILDID         specific buildid instead of iOS version (eg. 13C75)
  -B, --boardconfig BOARD       specific boardconfig instead of iPhone model (eg. n61ap)
  -h, --help                    prints usage information
  -o, --ota                     check OTA signing status, instead of normal restore
  -b, --no-baseband             don't check baseband signing status. Request a ticket without baseband
  -m, --build-manifest          manually specify buildmanifest. (can be used with -d)
  -s, --save                    save fetched shsh blobs (mostly makes sense with -e)
  -u, --update-install                  request update ticket instead of erase
  -l, --latest                  use latest public iOS version instead of manually specifying one
                                especially useful with -s and -e for saving blobs
  -e, --ecid ECID               manually specify ECID to be used for fetching blobs, instead of using random ones
                                ECID must be either dec or hex eg. 5482657301265 or ab46efcbf71
      --apnonce NONCE           manually specify APNONCE instead of using random one (not required for saving blobs)
      --sepnonce NONCE          manually specify SEPNONCE instead of using random one (not required for saving blobs)
      --save-path PATH          specify path for saving blobs
      --generator GEN           manually specify generator in format 0x%16llx
  -h, --help                    prints usage information
      --beta                    request ticket for beta instead of normal relase (use with -o)
      --list-devices            list all known devices
      --list-ios                list all known ios versions
      --nocache                 ignore caches and redownload required files
      --print-tss-request
      --print-tss-response
      --raw                     send raw file to Apple's tss server (useful for debugging)

Homepage: <https://github.com/encounter/tsschecker>

Administrator@GaChSrc MINGW64 ~/tsschecker

**Comment by encounter** [comment]
Great! 👍 

I'm also working on making it so the compiled .exe requires no extra DLLs. I'll post full build instructions along with that soon.

**Comment by xybp888** [comment]
ok!
We are looking forward to your update.
Thank you again!
