### ISSUE TITLE
Undocumented baseband "j121ap {"iPad7,2", 2315222105, 4}"

### ISSUE THREAD

**Issue by Squiddley** [encounter/tsschecker#8]
Hi - I am struggling to upgrade an ipad pro 2nd gen from 10.3.2 to 11.1.2 and failing miserably. After many reboots, V0rtexnonce seems to set the correct SHSH2 string. 

When running futurerestore using the command: "futurerestore.exe -t C:\Gash\futurerestore\11.1.2blob.shsh2 --latest-sep --latest-baseband C:\Gash\futurerestore\11.1.2.ipsw"

I get a promising outlook then once the ipad goes into recovery mode an error message: "[Error] getBNCHFromIM4M: BNCH size incorrect
waiting for nonce:
Got ApNonce from device: 00 2a 2d 5e 32 c3 40 01 ed de 01 da 13 a8 e8 01 66 a0 cf a4 59 e9 54 c6 02 23 a7 57 66 a7 ff 47"

Looking into the CMD window details, I am asked to report this issue with the baseband, so here it is. Any assistance to resolve the problem appreciated. I'm by no means a technical expert, but can follow instructions! Hoping to get to 11.1.2 before too late.

Cheers

**Comment by encounter** [comment]
Unfortunately, "BNCH size incorrect" means your SHSH blob is invalid. I added that check when I realized tsschecker was saving blobs incorrectly for A11 devices. TSSSaver, JailbreakBot and my fork of tsschecker have all been updated in the meantime, but sadly you won't be able to restore to 11.1.2.

The baseband information is useful though, thanks.

**Comment by encounter** [comment]
Baseband information added in a66b195cb8fb0e19d36304d300284f313b5cf970.

**Comment by Squiddley** [comment]
Does this mean I can update the iPad Pro to 11.1.2 now or I'm permanently closed out?

________________________________

**Comment by encounter** [comment]
Permanently closed out, sorry.

**Comment by Squiddley** [comment]
Thanks

________________________________
